### ISSUE TITLE
Error when running run.sh

### ISSUE THREAD

**Issue by jtoland** [andy-west/crt-vr-headset#1]
Hello,

I am currently getting the following error when running run.sh

root@raspberrypi:/home/pi/vr-test# sh run.sh
run.sh: 3: run.sh: run.sh: 5: run.sh: devilspie: not found
./head-tracking.py: Permission denied
Error: Failed to open I2C device /dev/i2c-0: No such file or directory (system:2)
[0218/210551.611639:ERROR:chrome_main_delegate.cc(627)] Web security may only be disabled if '--user-data-dir' is also specified.
[2281:2281:0218/210552.045145:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
run.sh: 8: kill: No such process

run.sh: 9: kill: No such process

run.sh: 10: kill: No such process

Can you please let me know what the issue could be.

Kind Regards,
Jason

**Comment by jtoland** [comment]
So i have figured out part of it but i now need to know where you got the modified minimu9-ahrs to bypas the no gyro error.
 4) Install modified minimu9-ahrs (bypass "No gyro found" error).

Please can you help

**Comment by andy-west** [comment]
Jason,

Apologies for not responding to your question right away.

I got it by [downloading the source](https://github.com/DavidEGrayson/minimu9-ahrs) from GitHub and changing it myself. In minimu9-ahrs.cpp there's a function main_with_exceptions that fails if there are missing sensors:

```
  if (missing)
  {
    if (missing.mag)
    {
      std::cerr << "Error: No magnetometer found." << std::endl;
    }
    if (missing.acc)
    {
      std::cerr << "Error: No accelerometer found." << std::endl;
    }
    if (missing.gyro)
    {
      std::cerr << "Error: No gyro found." << std::endl;
    }
    std::cerr << "Error: Needed sensors are missing." << std::endl;
    return 1;
  }
```

I'm pretty sure I just commented out the return 1; This whole thing is just a simple demo for a project video, so it's a bit klugey.

**Comment by jtoland** [comment]
Hello Andy,
I have tried that and got further but it seems there is more to this that meets the eye as i am now getting
Error: Failed to parse calibration file ~/.minimu9-ahrs-cal
I have touched this file to see if that would fix it but it has not.

I will have to sit down when i have some free time to figure it out.

Thanks for replying

**Comment by andy-west** [comment]
Ah, yes! You need to run minimu9-ahrs-calibrate and follow the directions. That should generate the file.

**Comment by jtoland** [comment]
Hello Andy,

I have run that but still, get errors about the gyro

pi@raspberrypi:~ $ minimu9-ahrs-calibrate
To calibrate the magnetometer, start rotating the IMU through
as many different orientations as possible.
Error: No gyro to read.
You can stop rotating the IMU now.
Warning: Only 0 readings were provided.
Traceback (most recent call last):
  File "/usr/bin/minimu9-ahrs-calibrator", line 103, in <module>
    run()
  File "/usr/bin/minimu9-ahrs-calibrator", line 79, in run
    cal = simple_minmax_calibration(raw_readings)
  File "/usr/bin/minimu9-ahrs-calibrator", line 98, in simple_minmax_calibration
    guess.extend([min(values), max(values)])
ValueError: min() arg is an empty sequence

**Comment by jtoland** [comment]
Hello,

I believe there is something within minimu9.cpp that needs to be disabled as well as this seems to be where the error is coming from that i am getting
